services:
  # Frontend Angular
  frontend:
    build:
      context: ./Angular_Clientes
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - orders-api
      - auth-api
    networks:
      - app-network
    restart: always

  # Orders API
  orders-api:
    build:
      context: ./Clientes_Pedidos_Service
      dockerfile: Dockerfile
    container_name: orders-api
    ports:
      - "5080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DBClientes_Pedidos;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True
    depends_on:
      - sqlserver
    networks:
      - app-network
    restart: always

  # Auth API
  auth-api:
    build:
      context: ./Clientes_pedidos_API
      dockerfile: Dockerfile
    container_name: auth-api
    ports:
      - "5081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DbBase;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True
      - Jwt__Key=${JWT_SECRET_KEY}
      - Jwt__Issuer=PlantHexApi
      - Jwt__Audience=PlantHexApiUsers
    depends_on:
      - sqlserver
    networks:
      - app-network
    restart: always

  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
    volumes:
      - sqlserver_data:/var/opt/mssql/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver_data:
